title: "本のタイトル"
summary: "本の紹介文"
topics: ["markdown", "zenn", "react"] # トピック（5つまで）
published: true # falseだと下書き
price: 3500 # 有料の場合200〜5000
chapters:
  - 1000視線 # チャプター1
  - 1010口 # チャプター2
  - example3 # チャプター3