title: "信頼関係構築エンジニアリング  ~心理学、論文をベースとした100の会話戦略~ "
summary: "
エンジニアにとって心理学は最高の武器になりますが、使える人はあまりいません。


心理学はコミュニケーションが発生するすべての場面で活用できる 汎用性の高い知識 で、
オンライン会議でもチャットでも1on1でも 複数の人がいれば必ず適応できるのが魅力です。

特に、スクラムフレームワークが導入されて以降、心理学はますます重要になりました。
心理学が使えれば、関わりのあるプロダクトと自身の保有する技術の表現力が上がり、上長や顧客との関係が改善され、結果的に評価も変わります。


ですが心理学を意識したコミュニケーションが取れるエンジニアはほぼいません。
理由は二つです。

1. コミュニケーションを重要だと思っているエンジニアが少ない （もちろん「表現力を磨く時間があれば技術力を磨きたい」という考え方は素晴らしい姿勢だと思います。）

2. 心理学の定理が多すぎて使いこなせない。


これらの課題をクリアし、全エンジニアにとって心理学の敷居を下げるために、本書は チートシート を導入しています。"
topics: ["markdown", "zenn", "react"] # トピック（5つまで）
published: false # falseだと下書き
price: 1000 # 有料の場合200〜5000
chapters:
  - readme
  - 1000eye     # 感情を読み取る
  - 1010mouse   # 感情を読み取る
  - 1100words
  - 1200chat
  - 2000write   # 書き込み操作
  - 2100likable # 好感度を上げる
  - 2100silent # 黙る
  #- 3000cases # ケース別対応策
  #- 3001cases # ケース別対応策1
  #- 3002cases # ケース別対応策2
  #- 3003cases # ケース別対応策3
  #- 3004cases # ケース別対応策4
  #- 3005cases # ケース別対応策5
  #- 4000users # ユーザーごとの対応

