title: "エンジニア心理学"
summary: "本の紹介文"
topics: ["markdown", "zenn", "react"] # トピック（5つまで）
published: false # falseだと下書き
price: 2500 # 有料の場合200〜5000
chapters:
  - readme
  - 1000eye # チャプター1
  - 1010mouse # チャプター2
  - 1100words
  - 1200chat
  - 2000write # 操りに行く
  - 3000cases # ケース別対応策

